languageCode = "en-us"
title = "Right to Counsel Jersey City"
baseURL = "https://righttocounseljc.org"
theme = "hugo-theme-massively"
googleanalytics = ""
disqusShortname = ""
disableKinds = ["taxonomy", "taxonomyTerm", "section"]

# [params]
 # 
  # set below parameter to define a favicon
  # favicon = "favicon.ico"
  # set to change date format
  # dateFormat = "2.1.2006"
backgroundPath = "images/bg.jpg"

# Below parameters can be set to override default post settings
[params.posts]
  featuredPost = false
#     folderName = "post"
#     pageSize = "6"
#     paginationPages = 2
#     showFirstLast = false
 
[languages]
[languages.en]
  languageName = "English"
[languages.es]
  languageName = "Español"
  title = "Derecho a un abogado - Jersey City"
#[languages.fr]
#  languageName = "Français"
#  title = "Massively - Version Française"

